### PR TITLE
Fix closing of backdrops of different overlay elements & add tests

### PR DESCRIPTION
**Pull request by zinkkrysty**
Bug described in #73

Moved responsability of tracking the backdrop and the active overlays with backdrops to the backdrop element.

### CODE REVIEW

**Comment by zinkkrysty** [comment]
I think I'm over my head here trying to fix this. I got stuck on testing if the backdrop is actually added to the DOM. I'm trying to add this:

```js
assert.isTrue(document.getElementsByTagName('iron-overlay-backdrop').length === 1, 'there is a backdrop in the DOM tree');
```

in the `runAfterOpen` callback, but it's failing to recognize the backdrop in the DOM, and I can't see it either in the element inspector.

Anyone willing to assist?

**Comment by valdrinkoshi** [comment]
if you try to do `elemet.tagName` you'll see that in some browsers it will be capitalized, so is better to use `document.querySelectorAll` instead of `document.getElementsByTagName`

**Comment by valdrinkoshi** [comment]
About the fix, I'm not sure we should be adding multiple `iron-overlay-backdrop` elements. 
Instead, we should keep only one for all the `iron-overlay-behavior` elements. So maybe we should generate it in the `iron-overlay-manager` instead of `iron-overlay-behavior`.
@cdata WDYT?

**Comment by zinkkrysty** [comment]
You are right, I realized my approach is not that good. I opened #79 with just the failing tests.

**Pull request closed without merging**
