### PR TITLE
Automatic cleanup!

### PR DESCRIPTION
**Pull request by e111077**

### CODE REVIEW

**Comment by bicknellr** [comment]
Looks like another case of `package-lock.json` being stale.

**Comment by e111077** [comment]
are you working on it or do you want me to do it?

**Comment by bicknellr** [comment]
I'm about to push.

**Comment by bicknellr** [comment]
I'm going to roll this one back too, since it didn't help.

**Comment by bicknellr** [comment]
Installing with npm v5.6.0 fixed this one too!

**Pull request merged**
