### PR TITLE
fix: make overlay display over backdrop, by appending overlay to body

### PR DESCRIPTION
**Pull request by timblack1**
Fixes https://github.com/PolymerElements/paper-dialog/issues/7
Fixes https://github.com/PolymerElements/polymer-starter-kit/issues/154
Fixes (maybe) https://github.com/PolymerElements/paper-dialog/issues/79
Fixes (maybe) https://github.com/PolymerElements/paper-dialog/issues/44
Fixes (maybe) https://github.com/PolymerElements/paper-drawer-panel/issues/122
Related to https://github.com/PolymerElements/iron-overlay-behavior/pull/72
Related to https://github.com/PolymerElements/iron-overlay-behavior/pull/86
Related to https://github.com/PolymerElements/iron-overlay-behavior/compare/backdrop-refit
Fixes (maybe) https://github.com/PolymerElements/paper-dialog-behavior/issues/78
Fixes https://github.com/PolymerLabs/app-layout/issues/155

### CODE REVIEW

**Comment by timblack1** [comment]
I signed it!

**Comment by valdrinkoshi** [comment]
Hi @timblack1, the current proposal has several drawbacks, e.g. it breaks style encapsulation. Also, the fact that you reparent it will cause `detach` and `attach` to be triggered, potentially entering in an infinite loop.

**Comment by timblack1** [comment]
Does https://github.com/PolymerElements/iron-overlay-behavior/blob/master/iron-overlay-backdrop.html#L99 break style encapsulation too?  That is the line which necessitates a fix like the one proposed here.

**Comment by valdrinkoshi** [comment]
Not really, as it is done if you explicitly call the method and if the element doesn't have a parent.
In essence it is suboptimal to attach, detach & attach elsewhere. This would cause query selectors to stop working, it would be a very breaking change.

I'm working on overcoming these stacking context related issues in the stacking-context branch. Happy to discuss the approach in a separate issue!

**Comment by timblack1** [comment]
I don't see an infinite loop in my manual testing of this proposed change.  I look forward to seeing a good resolution of the problem.

**Comment by valdrinkoshi** [comment]
The PR with the proposal is this one https://github.com/PolymerElements/iron-overlay-behavior/pull/155
Closing this PR.

**Comment by AliMD** [comment]
its works but its not a good way for solving problem, its like a hack dom. and maybe make problem with data binding, etc ...

**Pull request closed without merging**
