### PR TITLE
set canceled before setting opened flag

### PR DESCRIPTION
**Pull request by thansber**
Opening an overlay a 2nd time and closing it causes the closingReason.canceled flag to be set to false when it should be true.

https://github.com/PolymerElements/iron-overlay-behavior/issues/27

### CODE REVIEW

**Comment by thansber** [comment]
I signed it!

**Comment by valdrinkoshi** [comment]
@thansber looks good, could you add unit tests to avoid future regressions?

**Comment by thansber** [comment]
Sure thang.

**Comment by thansber** [comment]
I messed up this pull request and will start a new one with the fix + tests.

**Comment by valdrinkoshi** [comment]
sounds good, thanks!

**Pull request closed without merging**
