### PR TITLE
fix event param doc

### PR DESCRIPTION
**Pull request by morethanreal**
For https://github.com/PolymerElements/paper-dialog-behavior/issues/11

@garlicnation @jklein24 PTAL

### CODE REVIEW

**Comment by jklein24** [comment]
Is switching the type to {{canceled: (boolean|undefined)}} OK? What you have here works fine and the compiler doesn't even look at @event annotations, but it's nice to have more specific does if possible.

**Comment by morethanreal** [comment]
Yeah, that would be ok. I didn't write it this way in this PR because I have another behavior that includes this behavior that adds more keys to `closingReason`. Would I re-declare the event docs in the other behavior?

**Comment by jklein24** [comment]
I guess that's up to @garlicnation and the hydrolysis folks. JSCompiler doesn't care about event annotations either way as long as there aren't invalid `@param` annotations.

**Comment by garlicnation** [comment]
@jklein24 What's the recommended way to subclass in jscompiler? It seems like we'd want an "extends" or similar syntax for this use case.

**Comment by jklein24** [comment]
`@extends` is there, but I'm not sure that will really work correctly with the compiler for event types... Where are you thinking that annotation would go?

**Comment by garlicnation** [comment]
I was thinking the event type should get pulled out into a class or typedef, and referred to in this @param annotation, rather than being explicitly spelled out.

**Comment by morethanreal** [comment]
@garlicnation What's the syntax to do that?

**Comment by jklein24** [comment]
That sounds fine, but I'm still not sure where `@extends` would be useful

**Comment by morethanreal** [comment]
@jklein24 @garlicnation What should be my next steps for this PR?

**Comment by jklein24** [comment]
Either:

```
@event iron-overlay-closed
@param {{canceled: (boolean|undefined)}} detail ...
```

or extract the detail here into a typedef like:

```
/**
 * The detail object type for an iron-overlay-closed event.
 * canceled: True if the overlay was canceled.
 * @typedef {{canceled: (boolean|undefined)}}
 */
Polymer.IronOverlayBehaviorImpl.ClosedEventDetail;
```

**Pull request merged**
