### PR TITLE
Convert IronOverlayManager to a singleton class

### PR DESCRIPTION
**Pull request by rictic**

### CODE REVIEW

**Comment by cdata** [comment]
This is not a behavior. Is this annotation misleading?

**Comment by rictic** [comment]
Oh, it's not? Is it just a singleton object?

**Comment by zinkkrysty** [comment]
I think that the manager violates the SRP, as it both managing the overlay and the backdrops. The backdrop managing is not necessary since backdrops are shared only in some cases (when the element used is the same). But when 2 elements implement the iron-overlay-behavior, the backdrop isn't shared, instead they use 2 different backdrop elements. See #73 for more details.

That's why I believe that each backdrop should manage its own overlays and not let the manager do that.

**Comment by rictic** [comment]
Converted it from an object literal to a class with a single instantiation, PTAL.

@zinkkrysty this PR is just to explain what IronOverlayManager is doing to closure compiler. Please open an issue to debate the design.

**Comment by cdata** [comment]
@rictic @zinkkrysty :+1: Please open an issue to discuss!

**Comment by cdata** [comment]
@rictic this looks fine to me, but please co-ordinate this change with @valdrinkoshi since he has one or two PRs open that touch the same code.

**Comment by valdrinkoshi** [comment]
LGTM too
@rictic I'll merge this one and solve the conflicts on my side

**Comment by rictic** [comment]
Thanks!

**Pull request merged**
